### ISSUE TITLE
Could you add a branch uses GLFW and GLAD in the repository?

### ISSUE THREAD

**Issue by LiuZengqiang** [juliettef/GLFW-CMake-starter#3]
The code in this repository uses ``find_package(opengl REQUIRED)`` to locate the OpenGL libraries.
 It can also use the 'modern extension loader library,' such as ``glad``. Could you please add a branch in CMake that uses 'glfw' and 'glad'?

**Comment by dougbinks** [comment]
We don't have time to do this ourselves at the moment, but would welcome a contribution via a Pull Request.

**Comment by bozgi** [comment]
> We don't have time to do this ourselves at the moment, but would welcome a contribution via a Pull Request.

I believe that I correctly added the glad to CMakeLists.txt in #5

**Comment by dougbinks** [comment]
I'm closing this with the merging of @bozgi's PR #5.

We may want to add a branch or example using Glad in future, but for now at least this can help get people started more easily.
