### ISSUE TITLE
failed to configure

### ISSUE THREAD

**Issue by NikitaWeW** [juliettef/GLFW-CMake-starter#7]
GLFW-CMake-starter\build> cmake .. -G "MinGW Makefiles"
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/MinGW/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: opengl32
CMake Error at CMakeLists.txt:13 (add_subdirectory):
  The source directory

    H:/me/GLFW-CMake-starter/glfw

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!

**Comment by dougbinks** [comment]
It looks like you didn't clone the repository recursively as per the readme instructions, so don't have GLFW cloned.

Try:

`git submodule update --init --recursive`

Note: you need to be in the `GLFW-CMake-starter` directory for this to work as per normal with git.

**Comment by NikitaWeW** [comment]
thanks. that works. i will read instructions more carefully next time )
