### ISSUE TITLE
xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device

### ISSUE THREAD

**Issue by shoang22** [juliettef/GLFW-CMake-starter#8]
Hi, 

Thanks for developing this project, it's been really useful so far. One thing - after I execute `make all`, I attempt to run `./GLFW-CMake-starter`. When I do, a blank window opens, and I get the following error message:

`xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device`

Is this expected behavior? I'm attempting to run with WSL2.

**Comment by dougbinks** [comment]
I've not seen that error when running the test app on WSL2.

Can you change the colour of the window by changing the `glClearColor`? If so then the application is working and the error is potentially harmless, though searching for it might help find a solution - it looks like an X11 locale configuration issue.

**Comment by shoang22** [comment]
Changing `glClearColor` worked. Also, for those who are searching, I was able to get rid of the `xkbcommon` error by adding `LC_ALL=${LANG}` to my env per [these instructions](https://bbs.archlinux.org/viewtopic.php?id=228658).
